[build]
  base = "Landing"
  command = "npm install && npx ng build --configuration production"
  publish = "dist/aivent/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
